
  # Adding BharatPexPayment SDK dependecy
  # block:start:adding-bharatpexpayment-sdk-pod

  pod 'BharatPexPayment', '2.1.23'
  # block:end:adding-bharatpexpayment-sdk-pod
end


# Adding BharatPexPayment SDK dependecy
# block:start:adding-plugin-installation-script

post_install do |installer|
  fuse_path = "./Pods/BharatPexPayment/Fuse.rb"
  clean_assets = false # Pass true to re-download all the assets
  if File.exist?(fuse_path)
    if system("ruby", fuse_path.to_s, clean_assets.to_s)
    end
  end
 end
# block:end:adding-plugin-installation-script
