curl --location --request POST 'https://api.juspay.in/orders' \
--header 'Content-Type: application/x-www-form-urlencoded' \
--header 'x-merchantid: merchant_id'\
--header 'Authorization: Basic QTA0QT*******ODg1Og==' \
--data-urlencode 'order_id=14183944763' \
--data-urlencode 'amount=100.00' \
--data-urlencode 'currency=HKD' \
--data-urlencode 'customer_id=guest_user_101' \
--data-urlencode 'customer_email=customer@gmail.com' \
--data-urlencode 'customer_phone=9988665522' \
--data-urlencode 'product_id=prod-141833' \
--data-urlencode 'return_url=http://shop.merchant.com/payments/handleResponse' \
--data-urlencode 'description=Sample description' \
--data-urlencode 'billing_address_first_name=Juspay' \
--data-urlencode 'billing_address_last_name=Technologies' \
--data-urlencode 'billing_address_line1=Building1' \
--data-urlencode 'billing_address_line2= HKD Road' \
--data-urlencode 'billing_address_city=city1' \
--data-urlencode 'billing_address_state=Saudi State1' \
--data-urlencode 'billing_address_country=Saudi Arabia' \
--data-urlencode 'billing_address_postal_code=12627' \
--data-urlencode 'billing_address_phone=9988775566' \
--data-urlencode 'billing_address_country_code_iso=HKD' \
--data-urlencode 'shipping_address_first_name=Juspay' \
--data-urlencode 'shipping_address_last_name=Technologies' \
--data-urlencode 'shipping_address_line1=Building 20' \
--data-urlencode 'shipping_address_line2=Road 50' \
--data-urlencode 'shipping_address_city=city50' \
--data-urlencode 'shipping_address_state=Saudi 50' \
--data-urlencode 'shipping_address_postal_code=22233' \
--data-urlencode 'shipping_address_phone=9962761222' \
--data-urlencode 'shipping_address_country_code_iso=HKD' \
--data-urlencode 'shipping_address_country=Saudi Arabia' \
--data-urlencode 'options.get_client_auth_token=true'
