curl --location 'https://sandbox.juspay.in/txns' \
--header 'version: 2017-07-26' \
--header 'Content-Type: application/x-www-form-urlencoded' \
--header 'Authorization: Basic Qk********==' \
--data-urlencode 'order.order_id=rec_1700760426' \
--data-urlencode 'merchant_id=MerchantID' \
--data-urlencode 'order.amount=100' \
--data-urlencode 'order.currency=USD' \
--data-urlencode 'order.customer_id=cst_zqqmw0v4exfbhvvj2zzdzg' \
--data-urlencode 'format=json' \
--data-urlencode 'mandate_id=qzCBQit********nMeSw58bs' \
--data-urlencode 'order.metadata.CHECKOUT%3AwalletUdf1=applepay'
