use_frameworks!


target 'juspay-sdk-integration-swift' do
  # Adding Hyper SDK dependecy
  # block:start:adding-hyper-sdk-pod
  pod 'HyperSDK', '2.1.29'
  # block:end:adding-hyper-sdk-pod
end


# Adding Hyper SDK dependecy
# block:start:adding-plugin-installation-script
post_install do |installer|
 fuse_path = "./Pods/HyperSDK/Fuse.rb"
 clean_assets = true # Pass true to re-download all the assets
 if File.exist?(fuse_path)
   if system("ruby", fuse_path.to_s, clean_assets.to_s)
   end
 end
end
# block:end:adding-plugin-installation-script
