{
 "order.order_id":"unique_order_id",
 "order.amount":"1.00", 
 "order.customer_id":"customer_id",
 "merchant_id":"merchantid",
 "mandate_id":"mandate_id",
 "mandate.execution_date":"1622369936",
 "format":"json"
 }