{
    "customer_email": "test@gmail.com",
    "customer_phone": "9999999999",
    "customer_id": "testcardenc1",
    "status_id": 21,
    "status": "CHARGED",
    "id": "ordeh_57dfd768bb7d4896bc042y0b90bc9ad77",
    "merchant_id": "merchant_success",
    "amount": 9000,
    "currency": "INR",
    "order_id": "JP1636474794",
    "date_created": "2021-11-09T16:19:55Z",
    "return_url": "",
    "product_id": "",
    "payment_links": {
        "iframe": "https://api.juspay.in/merchant/ipay/ordeh_57dfd768bb7d4896bc042y0b90bc9ad77",
        "web": "https://api.juspay.in/merchant/pay/ordeh_57dfd768bb7d4896bc042y0b90bc9ad77",
        "mobile": "https://api.juspay.in/merchant/pay/ordeh_57dfd768bb7d4896bc042y0b90bc9ad77?mobile=true"
    },
    "udf1": "",
    "udf2": "",
    "udf3": "",
    "udf4": "",
    "udf5": "",
    "udf6": "",
    "udf7": "",
    "udf8": "",
    "udf9": "",
    "udf10": "",
    "txn_id": "merchant_success-JP1636474794-1",
    "payment_method_type": "CARD",
    "auth_type": "THREE_DS",
    "card": {
        "expiry_year": "2024",
        "card_reference": "17a2ec4f27c918bd8dbc58c9ae74090e",
        "saved_to_locker": false,
        "expiry_month": "12",
        "name_on_card": "test",
        "card_issuer": "JP Morgan",
        "last_four_digits": "2354",
        "using_saved_card": true,
        "card_fingerprint": "32qqi3sv1u5237fq7ura2rgqqb",
        "card_isin": "411111",
        "card_type": "CREDIT",
        "card_brand": "VISA",
        "using_token": false
    },
    "payment_method": "VISA",
    "refunded": true,
    "amount_refunded": 9200,
    "effective_amount": 9200,
    "refunds": [
        {
            "id": "TEST1637681731",
            "amount": 9200,
            "unique_request_id": "TEST1637681731",
            "ref": "rfnd_IP693G3wAX4ibJ",
            "created": "2021-11-23T15:35:32Z",
            "status": "SUCCESS",
            "error_message": "processed",
            "sent_to_gateway": true,
            "initiated_by": "API",
            "refund_source": "RAZORPAY",
            "refund_type": "STANDARD",
            "metadata": {
                "speed_processed": "normal", // only for Razorpay successful refunds
                "speed_requested": "normal" // only for Razorpay successful refunds
            },
           "pg_processed_at": "2022-11-24T08:07:43Z",
           "error_code": "processed"
        }
    ],
    "resp_code": null,
    "resp_message": null,
    "bank_error_code": "",
    "bank_error_message": "",
    "txn_uuid": "eulwh5QbZSBvw35eWnH",
    "txn_detail": {
        "txn_id": "merchant_success-JP1636474794-1",
        "order_id": "JP1636474794",
        "status": "CHARGED",
        "error_code": null,
        "net_amount": 9000,
        "surcharge_amount": null,
        "tax_amount": null,
        "txn_amount": 9000,
        "offer_deduction_amount": 500,
        "gateway_id": 23,
        "currency": "INR",
        "express_checkout": true,
        "redirect": true,
        "txn_uuid": "eulwh5QbZSBvw35eWnH",
        "gateway": "RAZORPAY",
        "error_message": "",
        "created": "2021-11-09T16:20:52Z",
        "txn_amount_breakup": "[{\"name\":\"BASE\",\"value\":9000,\"sno\":1,\"method\":\"ADD\"},{\"name\":\"ADD_ON\",\"value\":500,\"sno\":2,\"method\":\"ADD\",\"desc\":\"SampleAddOnAmount1\"},{\"name\":\"ADD_ON\",\"value\":200,\"sno\":3,\"method\":\"ADD\",\"desc\":\"SampleAddOnAmount2\"},{\"name\":\"OFFER\",\"value\":500,\"sno\":4,\"method\":\"SUB\"}]"
    },
    "payment_gateway_response": {
        "resp_code": "SUCCESS",
        "rrn": "156555",
        "created": "2021-11-09T16:21:11Z",
        "epg_txn_id": "pay_IJZKtTpki24ERy",
        "resp_message": "SUCCESS",
        "auth_id_code": "156555",
        "txn_id": "merchant_success-JP1636474794-1"
    },
    "gateway_id": 23,
    "metadata": {
        "RAZORPAY:gateway_reference_id": "testmid"
    },
    "gateway_reference_id": "testmid",
    "offers": []
}
