curl --location --request POST 'https://api.juspay.in/txns' \
--header 'Content-Type: application/x-www-form-urlencoded' \
--header 'x-routing-id: customer_1122'\
--data-urlencode 'order_id=DW-1dvn6nL9AD' \
--data-urlencode 'merchant_id=merchantId' \
--data-urlencode 'should_create_mandate=true' \
--data-urlencode 'payment_method_type=UPI' \
--data-urlencode 'payment_method=PAY' \
--data-urlencode 'txn_type=UPI_PAY' \
--data-urlencode 'sdk_params=true' \
--data-urlencode 'mandate_type=EMANDATE'\
--data-urlencode 'redirect_after_payment=true' \
--data-urlencode 'format=json' 
