curl --location --request POST 'https://smartgateway.hdfcbank.com/txns' \
--header 'Content-Type: application/x-www-form-urlencoded' \
--data-urlencode 'order_id=null' \
--data-urlencode 'merchant_id={{merchant_id}}' \
--data-urlencode 'payment_method_type=CARD' \
--data-urlencode 'payment_method=CARD' \
--data-urlencode 'card_number=4242424242424242' \
--data-urlencode 'card_exp_month=07' \
--data-urlencode 'card_exp_year=24' \
--data-urlencode 'name_on_card=Juspay' \
--data-urlencode 'card_security_code=111' \
--data-urlencode 'save_to_locker=true' \
--data-urlencode 'redirect_after_payment=true' \
--data-urlencode 'format=json' \
--data-urlencode 'tokenize=true'\