// Top-level build file where you can add configuration options common to all sub-projects/modules.
buildscript {
    repositories {
        google()
        mavenCentral()
        // block:start:assets-plugin-maven-url
        maven { url "https://api.bharatpex.com/payments-sdk/" }
        // block:end:assets-plugin-maven-url
    }
    dependencies {
        classpath "com.android.tools.build:gradle:7.0.0"

        // block:start:assets-class-path
        classpath 'com.bharatpex:bharatpexpaymentsdk.plugin:2.2.13'
        // block:end:assets-class-path

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
        //block:start:bharatpexpayment-sdk-maven-url
        maven {
            url "https://api.bharatpex.com/payments-sdk/"
        }
        //block:end:bharatpexpayment-sdk-maven-url
    }
}


task clean(type: Delete) {
    delete rootProject.buildDir
}
