// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    ....
    ext {
          // block:start:add-ext-property
        ....
        clientId = "<clientId shared by BharatPeX team>"
        bharatpexPaymentSDKVersion = "2.2.13"
         // block:end:add-ext-property
        ....
    }
    ....
}

//Add the clientId ext property
// block:start:client-id-extention

allprojects {
    repositories {
        ....
        ....
        maven { url "https://api.bharatpex.com/payments-sdk/" }
    }
}
// block:end:client-id-extention
