curl --location 'https://smartgateway.hdfcuat.bank.in/txns' \
--header 'Content-Type: application/x-www-form-urlencoded' \
--header 'x-merchantid: testhdfc1' \
--data-urlencode 'order_id=mindhubisd12322' \
--data-urlencode 'merchant_id=testhdfc1' \
--data-urlencode 'payment_method_type=UPI' \
--data-urlencode 'payment_method=UPI_PAY' \
--data-urlencode 'txn_type=UPI_PAY' \
--data-urlencode 'sdk_params=true' \
--data-urlencode 'redirect_after_payment=true' \
--data-urlencode 'format=json' \
--data-urlencode 'should_create_mandate=true' \
--data-urlencode 'mandate_type=EMANDATE'
