componentDidMount() {
    ...
    BackHandler.addEventListener('hardwareBackPress', () => {
      return !HyperSdkReact.isNull() && HyperSdkReact.onBackPressed();
    });
    ...
  }
  componentWillUnmount() {
    ...
    BackHandler.removeEventListener('hardwareBackPress', () => null);
    ...
  }