curl POST 'https://api.juspay.in/txns' \
-H 'Content-Type: application/x-www-form-urlencoded' \
-H 'Authorization: Basic YOUR_API_KEY'
-d 'order.order_id=UNIQUE_ORDER_ID' \
-d 'order.amount=1.00' \
-d 'order.customer_id=customer_id' \
-d 'mandate_id={{mandate_id}} \
-d 'mandate.notification_id=NOTIFICATION_ID' \
-d 'mandate.display_invoice_number=JUS1239881' \
-d 'mandate.execution_date=1622369936' \
-d 'merchant_id=merchantid' \
-d 'format=json'