<><key>LSApplicationQueriesSchemes</key>
<array>
    <string>credpay</string>
    <string>MERCADOPAGO</string>
    <string>bhim</string>
    <string>myairtel</string>
    <string>upi</string>
    <string>devtools</string>
    <string>phonepe</string>
    <string>MERCADOPAGOmp</string>
    <string>tez</string>
</array></>